export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_RECEIVED = 'BOOK_LIST_RECEIVED';
export const BOOK_LIST_ERROR = 'BOOK_LIST_ERROR';
export const BOOK_LIST_SET_PAGE = 'BOOK_LIST_SET_PAGE';
export const BOOK_LIST_SET_AUTHOR = 'BOOK_LIST_SET_AUTHOR';